use better script

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,3 +1,27 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-bundle exec rake db:migrate
+set -e            # fail fast
+set -o pipefail   # don't ignore exit codes when piping output
+
+# Configure directories
+build_dir=$1
+cache_dir=$2
+env_dir=$3
+
+blacklist_regex=${3:-'^(PATH|GIT_DIR|CPATH|CPPATH|LD_PRELOAD|LIBRARY_PATH)$'}
+if [ -d "$env_dir" ]; then
+  for e in $(ls $env_dir); do
+    echo "$e" | grep -qvE "$blacklist_regex" &&
+      export "$e=$(cat $env_dir/$e)"
+    :
+  done
+fi
+
+if [ -z "$DEPLOY_TASKS" ]; then
+  echo "DEPLOY_TASKS has not been set"
+  echo "You can set it with:"
+  echo 'heroku config:set DEPLOY_TASKS="tasks to run"'
+  exit 0
+fi
+
+cd $build_dir && bundle exec rake $DEPLOY_TASKS
